import { Component, OnInit } from '@angular/core';
import { trigger, style, animate, transition } from '@angular/animations';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-fun-popup',
  templateUrl: './fun-popup.component.html',
  styleUrls: ['./fun-popup.component.css'],
  standalone: true,
  imports: [CommonModule],
  animations: [
    trigger('popupAnim', [
      transition(':enter', [
        style({ opacity: 0, transform: 'scale(0.5)' }),
        animate('600ms ease-out', style({ opacity: 1, transform: 'scale(1)' })),
      ]),
      transition(':leave', [
        animate(
          '600ms ease-in',
          style({ opacity: 0, transform: 'scale(0.5)' })
        ),
      ]),
    ]),
  ],
})
export class FunPopupComponent implements OnInit {
  show = false;
  message = '';

  private messages = [
    'Bonne journée mon amour ❤️',
    'Je pense à toi 😘',
    'Tu rends ma vie plus belle 😍',
    'Toi + Moi = Toujours 💞',
    'Que ton sourire illumine ma journée 😇',
    'Tu es mon bonheur quotidien 🌸',
    'Je suis tellement chanceux(se) de t’avoir 💕',
    'Ton sourire est mon soleil ☀️',
    'Chaque jour avec toi est spécial ✨',
    'Tu es mon trésor le plus précieux 💎',
    'Je t’aime plus que les mots 💖',
    'Merci d’être dans ma vie 🌹',
    'Quand je pense à toi, je souris automatiquement 😊',
    'Mon cœur bat pour toi chaque instant 💓',
    'Tu es ma plus belle histoire d’amour 📖❤️',
    'Je veux passer tous mes jours avec toi 💍',
    'Ton amour est mon énergie 🔥',
    'Rien n’est plus beau que toi 🌷',
    'Je suis fier(ère) de t’avoir dans ma vie 🌟',
    'Toi et moi, c’est pour toujours 💫',
    'Tu rends mes journées douces comme du miel 🍯',
    'Ton regard est ma faiblesse 🥺',
    'Avec toi, tout est magique ✨',
    'Tu es la meilleure chose qui me soit arrivée 🎁',
    'J’ai hâte de te revoir 😍',
    'Ton câlin est mon endroit préféré 🤗',
    'Tu es mon rêve devenu réalité 🌙',
    'Chaque pensée de toi me rend heureux(se) 💞',
    'Je t’adore, tout simplement 💖',
    'Mon cœur t’appartient 💘',
    'Ton rire est ma mélodie préférée 🎶',
    'Je veux te garder dans mes bras pour toujours 🤍',
    'Même loin, tu es toujours près de mon cœur 📍❤️',
    'Tu es mon étoile qui brille dans la nuit 🌌',
    'Chaque moment avec toi est un cadeau 🎁',
    'Ton amour est mon abri 🏡💓',
    'Je suis accro à toi 💊😍',
    'Mon plus grand bonheur, c’est toi 💞',
    'Tu rends ma vie meilleure chaque jour 🌈',
    'Tu es ma moitié, mon tout, mon univers 🌍❤️',
    'Ton prénom est ma chanson préférée 🎵',
    'Je t’aime sans condition 💯❤️',
    'Tu es la plus belle personne du monde 🌹',
    'Rien ne vaut ton sourire 😊💕',
    'Avec toi je me sens complet(e) 🥰',
    'Ton amour est ma plus grande richesse 💎',
    'Je ne me lasserai jamais de toi 💖',
    'Tu rends mes rêves plus beaux 🌙✨',
    'Tu es la raison de mon sourire du matin ☀️',
    'Je veux te protéger pour toujours 🛡️❤️',
    'Tu es la douceur de ma vie 🍭',
    'Je me sens béni(e) de t’avoir 😇',
    'Ton amour me fait voler 🕊️',
    'Chaque baiser est un trésor 💋',
    'Tu es mon éternité ♾️❤️',
    'J’ai besoin de toi comme de l’air 🌬️',
    'Avec toi, je veux vieillir 👵👴❤️',
    'Tu es mon aventure préférée 🌍💑',
    'Tu es mon meilleur choix 💕',
    'Mon monde est plus beau grâce à toi 🌈',
    'Ton amour est ma force 💪❤️',
    'Je suis fou/folle de toi 🤯❤️',
    'Tu es mon miracle quotidien ✨',
    'Tu es mon refuge dans les tempêtes 🌧️❤️',
    'Rien ne me rend plus heureux(se) que toi 💖',
    'Tu es mon rayon de lumière 🌞',
    'Ton parfum me manque quand tu n’es pas là 🌸',
    'Je veux être à tes côtés pour toujours 🤝❤️',
    'Tu es mon ange gardien 👼',
    'Chaque seconde sans toi est trop longue ⏳💔',
    'Tu es mon coup de foudre éternel ⚡❤️',
    'Ton amour est ma plus belle aventure 🚀💞',
    'Je veux écrire notre histoire chaque jour ✍️❤️',
    'Je suis amoureux(se) de toi encore et encore 🔄❤️',
    'Tu es mon sourire préféré 😊❤️',
    'Ton amour est ma maison 🏠💕',
    'Avec toi, le monde est parfait 🌍✨',
    'Tu es mon feu dans le froid 🔥❄️',
    'Je t’aime plus qu’hier et moins que demain 🕰️❤️',
    'Tu es mon doux secret 🤫💖',
    'Mon cœur bat ton prénom 💓',
    'Tu es mon océan d’amour 🌊❤️',
    'Je suis perdu(e) dans tes yeux 💎👀',
    'Tu es ma chanson sans fin 🎶❤️',
    'Ton sourire guérit toutes mes blessures 💊💕',
    'Je veux t’aimer jusqu’à l’infini ♾️❤️',
    'Tu es mon plus beau cadeau de la vie 🎁💖',
    'Je suis complet(e) grâce à toi 🥰',
    'Ton amour est mon plus bel espoir 🌟',
    'Tu es mon âme sœur 💞',
    'Chaque jour avec toi est un conte de fées 🧚‍♀️✨',
    'Tu es mon bonheur éternel 💝',
    'Tu es ma plus belle vérité 🌹',
    'Mon seul désir, c’est toi 💘',
    'Je suis rien sans toi 💔➡️❤️',
    'Tu es ma flamme qui brûle toujours 🔥',
    'Avec toi, je me sens vivant(e) 🌈',
    'Je t’aimerai toujours, quoi qu’il arrive 🌍❤️',
    'Ton amour est ma destination 🗺️💞',
    'Tu es et tu resteras l’amour de ma vie ❤️',

    // English
    'Have a good day, my love ❤️',
    'I’m thinking of you 😘',
    'You make my life more beautiful 😍',
    'You + Me = Forever 💞',
    'May your smile brighten my day 😇',
    'You are my daily happiness 🌸',
    'I’m so lucky to have you 💕',
    'Your smile is my sunshine ☀️',
    'Every day with you is special ✨',
    'You are my most precious treasure 💎',
    'I love you more than words 💖',
    'Thank you for being in my life 🌹',
    'When I think of you, I automatically smile 😊',
    'My heart beats for you every moment 💓',
    'You are my most beautiful love story 📖❤️',
    'I want to spend all my days with you 💍',
    'Your love is my energy 🔥',
    'Nothing is more beautiful than you 🌷',
    'I’m proud to have you in my life 🌟',
    'You and me, it’s forever 💫',
    'You make my days sweet like honey 🍯',
    'Your gaze is my weakness 🥺',
    'With you, everything is magical ✨',
    'You are the best thing that ever happened to me 🎁',
    'I can’t wait to see you again 😍',
    'Your hug is my favorite place 🤗',
    'You are my dream come true 🌙',
    'Every thought of you makes me happy 💞',
    'I adore you, simply 💖',
    'My heart belongs to you 💘',
    'Your laughter is my favorite melody 🎶',
    'I want to hold you in my arms forever 🤍',
    'Even far away, you’re always close to my heart 📍❤️',
    'You are my star shining in the night 🌌',
    'Every moment with you is a gift 🎁',
    'Your love is my shelter 🏡💓',
    'I’m addicted to you 💊😍',
    'My greatest happiness is you 💞',
    'You make my life better every day 🌈',
    'You are my half, my everything, my universe 🌍❤️',
    'Your name is my favorite song 🎵',
    'I love you unconditionally 💯❤️',
    'You are the most beautiful person in the world 🌹',
    'Nothing is worth more than your smile 😊💕',
    'With you I feel complete 🥰',
    'Your love is my greatest wealth 💎',
    'I’ll never get tired of you 💖',
    'You make my dreams more beautiful 🌙✨',
    'You are the reason for my morning smile ☀️',
    'I want to protect you forever 🛡️❤️',
    'You are the sweetness of my life 🍭',
    'I feel blessed to have you 😇',
    'Your love makes me fly 🕊️',
    'Every kiss is a treasure 💋',
    'You are my eternity ♾️❤️',
    'I need you like air 🌬️',
    'With you, I want to grow old 👵👴❤️',
    'You are my favorite adventure 🌍💑',
    'You are my best choice 💕',
    'My world is more beautiful thanks to you 🌈',
    'Your love is my strength 💪❤️',
    'I’m crazy about you 🤯❤️',
    'You are my daily miracle ✨',
    'You are my refuge in storms 🌧️❤️',
    'Nothing makes me happier than you 💖',
    'You are my ray of light 🌞',
    'I miss your scent when you’re not here 🌸',
    'I want to be by your side forever 🤝❤️',
    'You are my guardian angel 👼',
    'Every second without you is too long ⏳💔',
    'You are my eternal love at first sight ⚡❤️',
    'Your love is my greatest adventure 🚀💞',
    'I want to write our story every day ✍️❤️',
    'I’m in love with you over and over again 🔄❤️',
    'You are my favorite smile 😊❤️',
    'Your love is my home 🏠💕',
    'With you, the world is perfect 🌍✨',
    'You are my fire in the cold 🔥❄️',
    'I love you more than yesterday and less than tomorrow 🕰️❤️',
    'You are my sweet secret 🤫💖',
    'My heart beats your name 💓',
    'You are my ocean of love 🌊❤️',
    'I’m lost in your eyes 💎👀',
    'You are my endless song 🎶❤️',
    'Your smile heals all my wounds 💊💕',
    'I want to love you to infinity ♾️❤️',
    'You are my most beautiful gift in life 🎁💖',
    'I am complete thanks to you 🥰',
    'Your love is my greatest hope 🌟',
    'You are my soulmate 💞',
    'Every day with you is a fairy tale 🧚‍♀️✨',
    'You are my eternal happiness 💝',
    'You are my most beautiful truth 🌹',
    'My only desire is you 💘',
    'I am nothing without you 💔➡️❤️',
    'You are my flame that always burns 🔥',
    'With you, I feel alive 🌈',
    'I will always love you, no matter what 🌍❤️',
    'Your love is my destination 🗺️💞',
    'You are and will always be the love of my life ❤️',
  ];

  ngOnInit() {
    const intervalMinutes = 30;

    const checkAndShow = () => {
      const now = Date.now();
      const lastShown = localStorage.getItem('fun-popup-timestamp');
      const lastShownTime = lastShown ? parseInt(lastShown, 10) : 0;

      if (now - lastShownTime > intervalMinutes * 60 * 1000) {
        this.show = true;
        this.message =
          this.messages[Math.floor(Math.random() * this.messages.length)];

        localStorage.setItem('fun-popup-timestamp', now.toString());

        setTimeout(() => (this.show = false), 4000);
      }
    };

    checkAndShow();

    setInterval(checkAndShow, 60 * 1000);
  }

  close() {
    this.show = false;
  }
}
